title: Julius Häger
description: My portfolio
author: "Julius Häger"

github_username:  NogginBops

url: "https://nogginbops.github.io"

plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-remote-theme

include:
  - README.md

#theme: minima
remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%Y-%m-%d"